#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Aug 22, 2022 12:20:27 PM +0530  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import keylogger_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("633x430+584+369")
        top.minsize(120, 1)
        top.maxsize(4644, 1161)
        top.resizable(1,  1)
        top.title("Keylogger v2 - by @hirushaadi")
        top.configure(background="#1e1e1e")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.sub_menu = tk.Menu(top, activebackground='beige', activeborderwidth=1
                ,activeforeground='black', background='#d9d9d9', borderwidth=1
                ,disabledforeground='#a3a3a3', foreground='#000000', tearoff=0)
        self.menubar.add_cascade(compound='left', label='Menu', menu=self.sub_menu
                ,)
        self.sub_menu.add_command(compound='left',label='Save')
        self.sub_menu.add_command(compound='left',label='Build')
        self.sub_menu1 = tk.Menu(top, activebackground='beige'
                ,activeborderwidth=1, activeforeground='black'
                ,background='#d9d9d9', borderwidth=1, disabledforeground='#a3a3a3'
                ,foreground='#000000', tearoff=0)
        self.menubar.add_cascade(compound='left', label='Actions'
                ,menu=self.sub_menu1, )
        self.sub_menu1.add_command(compound='left',label='Build')
        self.sub_menu1.add_separator()
        self.sub_menu1.add_command(compound='left',label='Reset')
        self.sub_menu12 = tk.Menu(top, activebackground='beige'
                ,activeborderwidth=1, activeforeground='black'
                ,background='#d9d9d9', borderwidth=1, disabledforeground='#a3a3a3'
                ,foreground='#000000', tearoff=0)
        self.menubar.add_cascade(compound='left', label='Other'
                ,menu=self.sub_menu12, )
        self.sub_menu12.add_command(compound='left',label='Source Code')
        self.sub_menu12.add_command(compound='left',label='About')
        self.sub_menu12.add_command(compound='left',label='Help')

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.032, rely=0.256, relheight=0.291
                , relwidth=0.261)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(cursor="fleur")

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.032, rely=0.14, height=30, relwidth=0.37)
        self.Entry1.configure(background="#191919")
        self.Entry1.configure(cursor="fleur")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#ffffff")
        self.Entry1.configure(insertbackground="black")

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.032, rely=0.093, height=21, width=164)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#1e1e1e")
        self.Label1.configure(compound='left')
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Label1.configure(foreground="#49b618")
        self.Label1.configure(text='''Executable Name:''')

def start_up():
    keylogger_support.main()

if __name__ == '__main__':
    keylogger_support.main()




